# Generated by Django 4.2 on 2023-10-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
