# Generated by Django 4.2 on 2023-10-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_fileitem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
