version: '2.4'

services:
  postgres:
      build: ./docker_configs/confs/postgres
      restart: unless-stopped
      command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=1440 -c log_rotation_size=0 -c log_filename='postgresql-%d.log'
      ports:
        - ${DB_PORT}:5432
      volumes:
        - ../mounts/postgres_data:/var/lib/postgresql/data
        - ../mounts/postgres_backups:/backups
      environment:
        PGDATA: /var/lib/postgresql/data
        POSTGRES_HOST: ${DB_HOST}
        POSTGRES_PORT: 5432
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      env_file:
        - .env

  master_bot:
    command: /commands/master_bot.sh
    extends:
      file: common.yml
      service: web_base
    env_file:
      - .env
    depends_on:
      - postgres
#      - redis
#

  web:
    command: /commands/admin.sh
    extends:
      file: common.yml
      service: web_base
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      - postgres
#      - redis



